Expand spring-security fuzzing
CodeIntelligenceTesting/oss-fuzz pull request #13
Opened 2022-08-17 11:52 UTC by CheeseHunter117

Added fuzz targets for:
- crypto.util.EncodingUtils.concatenate
- crypto.codec.Hex.encode and crypto.codec.Hex.decode
- crypto.codec.Utf8.encode and crypto.codec.Utf8.decode
- provisioning.InMemoryUserDetailsManager.changePassword

2022-08-17 11:53 UTC, CheeseHunter117 commented
@onionpsy Please review

2022-08-25 11:40 UTC, onionpsy requested changes

2022-08-25 11:40 UTC, onionpsy commented on projects/spring-security/EncodingUtilsConcatenateFuzzer.java
> +    // Values chosen without heuristics or logic
I would remove this comment

2022-08-25 11:40 UTC, onionpsy commented on projects/spring-security/HexFuzzer.java
> +                throw new FuzzerSecurityIssueHigh("Hex value has changed during encoding and decoding");
`FuzzerSecurityIssueHigh` is probably a bit too much, I would set to low or medium

2022-08-25 11:40 UTC, onionpsy commented on projects/spring-security/InMemoryUserDetailsManagerChangePasswordFuzzer.java
> +    // Values chosen without heuristics or logic
Same here

2022-08-25 11:40 UTC, onionpsy commented on projects/spring-security/InMemoryUserDetailsManagerChangePasswordFuzzer.java
> +        // SecurityContextHolder.getContext().setAuthentication(UsernamePasswordAuthenticationToken.unauthenticated(USERNAME, PASSWORD));
Please removed commented code

2022-08-25 11:40 UTC, onionpsy commented on projects/spring-security/InMemoryUserDetailsManagerChangePasswordFuzzer.java
> +            throw new FuzzerSecurityIssueHigh("The user disappeared from the InMemoryUserDetailsManager");
Probably more a bug than a security if it reach that point. We don't have a "bug" exception in jazzer so I would just throw a security low here

2022-08-25 11:40 UTC, onionpsy commented on projects/spring-security/Utf8Fuzzer.java
> +                throw new FuzzerSecurityIssueHigh("Utf8 value has changed during encoding and decoding");
Same here, high is a bit too much

2022-08-25 11:59 UTC, merged